name: Docker Build
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: push-info
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: renbot/multichain:${{ steps.push-info.outputs.tag }}, renbot/multichain:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
